export {
  DEFAULT_GALLERY_VALUE,
  GALLERY_HEADING_LINE1_DEFAULT,
  GALLERY_HEADING_LINE1_PATH,
  GALLERY_HEADING_LINE2_DEFAULT,
  GALLERY_HEADING_LINE2_PATH,
  GALLERY_ITEMS_PATH,
  GALLERY_LEAD_DEFAULT,
  GALLERY_LEAD_PATH,
  GALLERY_SLIDES_PATH,
  createGallerySlide,
  galleryHeadingLine1,
  galleryHeadingLine2,
  galleryLead,
  galleryValueSchema,
  moveArrayItem,
  parseGalleryValue,
  serializeGalleryValue,
  type GallerySlide,
  type GalleryValue,
} from "@/lib/content/fields/gallery"
