import type { CategoryIconId } from "@/lib/content/fields/category-icon"
import { cn } from "@/lib/utils"
import {
  Anchor,
  Bean,
  Bolt,
  Box,
  Boxes,
  Building2,
  Cloud,
  Cog,
  Cone,
  Construction,
  Container,
  Droplets,
  Factory,
  Filter,
  Flame,
  Forklift,
  Fuel,
  Gauge,
  Grid3x3,
  Hammer,
  HardHat,
  Home,
  Landmark,
  Layers,
  LayoutGrid,
  Leaf,
  Mountain,
  Network,
  Nut,
  Package,
  Pickaxe,
  Recycle,
  Route,
  Ruler,
  Scale,
  Settings,
  Ship,
  Shovel,
  Signpost,
  Snowflake,
  Sprout,
  Store,
  Sun,
  Thermometer,
  TowerControl,
  Truck,
  UtilityPole,
  Warehouse,
  Waves,
  Wheat,
  Wind,
  Workflow,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react"

const CATEGORY_ICON_COMPONENTS: Record<CategoryIconId, LucideIcon> = {
  anchor: Anchor,
  bean: Bean,
  bolt: Bolt,
  box: Box,
  boxes: Boxes,
  "building-2": Building2,
  cloud: Cloud,
  cog: Cog,
  cone: Cone,
  construction: Construction,
  container: Container,
  droplets: Droplets,
  factory: Factory,
  filter: Filter,
  flame: Flame,
  forklift: Forklift,
  fuel: Fuel,
  gauge: Gauge,
  "grid-3x3": Grid3x3,
  hammer: Hammer,
  "hard-hat": HardHat,
  home: Home,
  landmark: Landmark,
  layers: Layers,
  "layout-grid": LayoutGrid,
  leaf: Leaf,
  mountain: Mountain,
  network: Network,
  nut: Nut,
  package: Package,
  pickaxe: Pickaxe,
  recycle: Recycle,
  route: Route,
  ruler: Ruler,
  scale: Scale,
  settings: Settings,
  ship: Ship,
  shovel: Shovel,
  signpost: Signpost,
  snowflake: Snowflake,
  sprout: Sprout,
  store: Store,
  sun: Sun,
  thermometer: Thermometer,
  "tower-control": TowerControl,
  truck: Truck,
  "utility-pole": UtilityPole,
  warehouse: Warehouse,
  waves: Waves,
  wheat: Wheat,
  wind: Wind,
  workflow: Workflow,
  wrench: Wrench,
  zap: Zap,
}

type CategoryIconProps = {
  icon: CategoryIconId
  className?: string
}

export function CategoryIcon({ icon, className }: CategoryIconProps) {
  const Icon = CATEGORY_ICON_COMPONENTS[icon]
  return <Icon className={cn("size-6 shrink-0", className)} />
}
