/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as EditarRouteImport } from './routes/editar'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutosCategoriaRouteImport } from './routes/produtos/$categoria'
import { Route as ProdutosCategoriaIdRouteImport } from './routes/produtos/$categoria/$id'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc/$'
import { Route as ApiContentAssetsSplatRouteImport } from './routes/api/content-assets/$'

const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const EditarRoute = EditarRouteImport.update({
  id: '/editar',
  path: '/editar',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosCategoriaRoute = ProdutosCategoriaRouteImport.update({
  id: '/$categoria',
  path: '/$categoria',
  getParentRoute: () => ProdutosRoute,
} as any)
const ProdutosCategoriaIdRoute = ProdutosCategoriaIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProdutosCategoriaRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContentAssetsSplatRoute = ApiContentAssetsSplatRouteImport.update({
  id: '/api/content-assets/$',
  path: '/api/content-assets/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/editar': typeof EditarRoute
  '/produtos': typeof ProdutosRouteWithChildren
  '/produtos/$categoria': typeof ProdutosCategoriaRouteWithChildren
  '/api/content-assets/$': typeof ApiContentAssetsSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/produtos/$categoria/$id': typeof ProdutosCategoriaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/editar': typeof EditarRoute
  '/produtos': typeof ProdutosRouteWithChildren
  '/produtos/$categoria': typeof ProdutosCategoriaRouteWithChildren
  '/api/content-assets/$': typeof ApiContentAssetsSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/produtos/$categoria/$id': typeof ProdutosCategoriaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/editar': typeof EditarRoute
  '/produtos': typeof ProdutosRouteWithChildren
  '/produtos/$categoria': typeof ProdutosCategoriaRouteWithChildren
  '/api/content-assets/$': typeof ApiContentAssetsSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/produtos/$categoria/$id': typeof ProdutosCategoriaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/editar'
    | '/produtos'
    | '/produtos/$categoria'
    | '/api/content-assets/$'
    | '/api/rpc/$'
    | '/produtos/$categoria/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/editar'
    | '/produtos'
    | '/produtos/$categoria'
    | '/api/content-assets/$'
    | '/api/rpc/$'
    | '/produtos/$categoria/$id'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/editar'
    | '/produtos'
    | '/produtos/$categoria'
    | '/api/content-assets/$'
    | '/api/rpc/$'
    | '/produtos/$categoria/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRoute
  EditarRoute: typeof EditarRoute
  ProdutosRoute: typeof ProdutosRouteWithChildren
  ApiContentAssetsSplatRoute: typeof ApiContentAssetsSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editar': {
      id: '/editar'
      path: '/editar'
      fullPath: '/editar'
      preLoaderRoute: typeof EditarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/$categoria': {
      id: '/produtos/$categoria'
      path: '/$categoria'
      fullPath: '/produtos/$categoria'
      preLoaderRoute: typeof ProdutosCategoriaRouteImport
      parentRoute: typeof ProdutosRoute
    }
    '/produtos/$categoria/$id': {
      id: '/produtos/$categoria/$id'
      path: '/$id'
      fullPath: '/produtos/$categoria/$id'
      preLoaderRoute: typeof ProdutosCategoriaIdRouteImport
      parentRoute: typeof ProdutosCategoriaRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/content-assets/$': {
      id: '/api/content-assets/$'
      path: '/api/content-assets/$'
      fullPath: '/api/content-assets/$'
      preLoaderRoute: typeof ApiContentAssetsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProdutosCategoriaRouteChildren {
  ProdutosCategoriaIdRoute: typeof ProdutosCategoriaIdRoute
}

const ProdutosCategoriaRouteChildren: ProdutosCategoriaRouteChildren = {
  ProdutosCategoriaIdRoute: ProdutosCategoriaIdRoute,
}

const ProdutosCategoriaRouteWithChildren =
  ProdutosCategoriaRoute._addFileChildren(ProdutosCategoriaRouteChildren)

interface ProdutosRouteChildren {
  ProdutosCategoriaRoute: typeof ProdutosCategoriaRouteWithChildren
}

const ProdutosRouteChildren: ProdutosRouteChildren = {
  ProdutosCategoriaRoute: ProdutosCategoriaRouteWithChildren,
}

const ProdutosRouteWithChildren = ProdutosRoute._addFileChildren(
  ProdutosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRoute,
  EditarRoute: EditarRoute,
  ProdutosRoute: ProdutosRouteWithChildren,
  ApiContentAssetsSplatRoute: ApiContentAssetsSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
