/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as EditarRouteImport } from './routes/editar'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CodigoEticaRouteImport } from './routes/codigo-etica'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc/$'
import { Route as ApiContentAssetsSplatRouteImport } from './routes/api/content-assets/$'

const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const EditarRoute = EditarRouteImport.update({
  id: '/editar',
  path: '/editar',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CodigoEticaRoute = CodigoEticaRouteImport.update({
  id: '/codigo-etica',
  path: '/codigo-etica',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContentAssetsSplatRoute = ApiContentAssetsSplatRouteImport.update({
  id: '/api/content-assets/$',
  path: '/api/content-assets/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/codigo-etica': typeof CodigoEticaRoute
  '/contato': typeof ContatoRoute
  '/demo': typeof DemoRoute
  '/editar': typeof EditarRoute
  '/produtos': typeof ProdutosRoute
  '/api/content-assets/$': typeof ApiContentAssetsSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/codigo-etica': typeof CodigoEticaRoute
  '/contato': typeof ContatoRoute
  '/demo': typeof DemoRoute
  '/editar': typeof EditarRoute
  '/produtos': typeof ProdutosRoute
  '/api/content-assets/$': typeof ApiContentAssetsSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/codigo-etica': typeof CodigoEticaRoute
  '/contato': typeof ContatoRoute
  '/demo': typeof DemoRoute
  '/editar': typeof EditarRoute
  '/produtos': typeof ProdutosRoute
  '/api/content-assets/$': typeof ApiContentAssetsSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalogo'
    | '/codigo-etica'
    | '/contato'
    | '/demo'
    | '/editar'
    | '/produtos'
    | '/api/content-assets/$'
    | '/api/rpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalogo'
    | '/codigo-etica'
    | '/contato'
    | '/demo'
    | '/editar'
    | '/produtos'
    | '/api/content-assets/$'
    | '/api/rpc/$'
  id:
    | '__root__'
    | '/'
    | '/catalogo'
    | '/codigo-etica'
    | '/contato'
    | '/demo'
    | '/editar'
    | '/produtos'
    | '/api/content-assets/$'
    | '/api/rpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogoRoute: typeof CatalogoRoute
  CodigoEticaRoute: typeof CodigoEticaRoute
  ContatoRoute: typeof ContatoRoute
  DemoRoute: typeof DemoRoute
  EditarRoute: typeof EditarRoute
  ProdutosRoute: typeof ProdutosRoute
  ApiContentAssetsSplatRoute: typeof ApiContentAssetsSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editar': {
      id: '/editar'
      path: '/editar'
      fullPath: '/editar'
      preLoaderRoute: typeof EditarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codigo-etica': {
      id: '/codigo-etica'
      path: '/codigo-etica'
      fullPath: '/codigo-etica'
      preLoaderRoute: typeof CodigoEticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/content-assets/$': {
      id: '/api/content-assets/$'
      path: '/api/content-assets/$'
      fullPath: '/api/content-assets/$'
      preLoaderRoute: typeof ApiContentAssetsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogoRoute: CatalogoRoute,
  CodigoEticaRoute: CodigoEticaRoute,
  ContatoRoute: ContatoRoute,
  DemoRoute: DemoRoute,
  EditarRoute: EditarRoute,
  ProdutosRoute: ProdutosRoute,
  ApiContentAssetsSplatRoute: ApiContentAssetsSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
